stages:
  - build
  - deploy_test
  - test
  - promote


Kubekat Docker Build:
  stage: build
  services:
  - docker:dind
  script:
    - DOCKER_HOST=tcp://localhost:2375
    - export DOCKER_HOST
    - CI_REGISTRY=hub.docker.com
    - CI_REGISTRY_USER=sendotux
    - CI_REGISTRY_PASSWORD=$DOCKER_HUB_PASSWORD
    - CI_REGISTRY_IMAGE=kubekat-ui
    - CI_COMMIT_TAG=latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - cd library
    - docker build -t sendotux/kubekat-ui:latest -f kubekat_ui/Dockerfile . && docker push sendotux/kubekat-ui:latest
    - docker build -t sendotux/kubekat-pvc-checker:latest -f kubekat_pvc_checker/Dockerfile . && docker push sendotux/kubekat-pvc-checker:latest
    - docker build -t sendotux/kubekat-label-checker:latest -f kubekat_label_checker/Dockerfile . && docker push sendotux/kubekat-label-checker:latest


Deploy on Test:
  stage: deploy_test
  script:
  - ls -la
  - kubectl -n kubekat patch deployment kubekat-ui -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-pvc-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-label-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  environment:
    name: kubekat.home.sendotux.net 
    url: https://kubekat.home.sendotux.net

Test pvc HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/pvc
Test label HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/label
Test about HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/about


Deploy on Acceptance:
  stage: promote
  script:
  - kubectl -n kubekat patch deployment kubekat-ui -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-pvc-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-label-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  environment:
    name: acceptance
    url: https://kubekat.home.sendotux.net
  when: manual
  only:
  - master


Deploy on Production:
  stage: promote
  script:
  - kubectl -n kubekat patch deployment kubekat-ui -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-pvc-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-label-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  environment:
    name: production
    url: https://kubekat.home.sendotux.net
  when: manual
  only:
  - master


