stages:
  - preparation
  - build
  - test
  - final
  
Pre:
  stage: preparation
  script:
  - woops=$RANDOM
  - echo $whoops
  - kubectl create namespace testing
  - kubectl -n testing get pods

Build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - CI_REGISTRY=hub.docker.com
    - CI_REGISTRY_USER=sendotux
    - CI_REGISTRY_PASSWORD=BLABLABLA
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  
Job3:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/pvc
 
Final:
  stage: final
  script:
  - kubectl delete namespace testing
  - echo $whoops
