stages:
  - preparation
  - build
  - test
  - final
  
Pre:
  stage: preparation
  script:
  - kubectl create namespace testing
  - kubectl -n testing get pods

Job1:
  stage: build
  script:
  - echo docker ps
  
Job2:
  stage: build
  script:
  - echo docker images
  
Job3:
  stage: test
  script:
  - curl -IL https://kubekat.home.sendotux.net/pvc
 
Final:
  stage: final
  script:
  - kubectl delete namespace testing
  
