stages:
  - build
  - deploy_test
  - test
  - promote


Docker_Build:
  stage: build
  services:
  - docker:dind
  script:
    - DOCKER_HOST=tcp://localhost:2375
    - export DOCKER_HOST
    - CI_REGISTRY=hub.docker.com
    - CI_REGISTRY_USER=sendotux
    - CI_REGISTRY_PASSWORD=$DOCKER_HUB_PASSWORD
    - CI_REGISTRY_IMAGE=kubekat-ui
    - CI_COMMIT_TAG=latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - cd library
    - docker build -t sendotux/kubekat-ui:latest -f kubekat_ui/Dockerfile . && docker push sendotux/kubekat-ui:latest
    - docker build -t sendotux/kubekat-pvc-checker:latest -f kubekat_pvc_checker/Dockerfile . && docker push sendotux/kubekat-pvc-checker:latest
    - docker build -t sendotux/kubekat-label-checker:latest -f kubekat_label_checker/Dockerfile . && docker push sendotux/kubekat-label-checker:latest


Deploy_Test:
  stage: deploy_test
  script:
  - ls -la
  - kubectl -n kubekat apply -f library/kubekat_ui/kubernetes/deployment.yaml
  - kubectl -n kubekat apply -f library/kubekat_pvc_checker/kubernetes/deployment.yaml
  - kubectl -n kubekat apply -f library/kubekat_label_checker/kubernetes/deployment.yaml
  
  - kubectl -n kubekat patch deployment kubekat-ui -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-pvc-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-label-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  environment:
    name: test
    url: https://kubekat.home.sendotux.net
    on_stop: Stop_Test
    
Stop_Test:
  stage: deploy_test
  script:
  - kubectl -n kubekat delete -f library/kubekat_ui/kubernetes/deployment.yaml
  - kubectl -n kubekat delete -f library/kubekat_pvc_checker/kubernetes/deployment.yaml
  - kubectl -n kubekat delete -f library/kubekat_label_checker/kubernetes/deployment.yaml
  when: manual
  environment:
    name: test
    action: stop

Test_pvc_HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/pvc
Test_label_HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/label
Test_about_HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/about


Deploy_Acceptance:
  stage: promote
  script:
  - kubectl -n kubekat patch deployment kubekat-ui -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-pvc-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-label-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  environment:
    name: acceptance
    url: https://kubekat.home.sendotux.net
  when: manual
  only:
  - master


Deploy_Production:
  stage: promote
  script:
  - kubectl -n kubekat patch deployment kubekat-ui -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-pvc-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl -n kubekat patch deployment kubekat-label-checker -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
  environment:
    name: production
    url: https://kubekat.home.sendotux.net
  when: manual
  only:
  - master


