stages:
  - preparation
  - build
  - test
  - final
  
Pre-steps:
  stage: preparation
  allow_failure: true
  script:
  - env
  - kubectl create namespace testing
  - echo kubectl -n testing get pods


Kubekat Docker Build:
  stage: build
  services:
  - docker:dind
  script:
    - DOCKER_HOST=tcp://localhost:2375
    - export DOCKER_HOST
    - CI_REGISTRY=hub.docker.com
    - CI_REGISTRY_USER=sendotux
    - CI_REGISTRY_PASSWORD=$DOCKER_HUB_PASSWORD
    - CI_REGISTRY_IMAGE=kubekat-ui
    - CI_COMMIT_TAG=latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - cd library && docker build -t sendotux/kubekat-ui-checker:latest -f kubekat_ui/Dockerfile . && docker push sendotux/kubekat-ui-checker:latest
    - cd library && docker build -t sendotux/kubekat-pvc-checker:latest -f kubekat_pvc/Dockerfile . && docker push sendotux/kubekat-pvc-checker:latest
    - cd library && docker build -t sendotux/kubekat-label-checker:latest -f kubekat_label/Dockerfile . && docker push sendotux/kubekat-label-checker:latest




Test pvc HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/pvc
Test label HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/label
Test about HTTPS:
  stage: test
  script:
  - curl -sSIL https://kubekat.home.sendotux.net/about



End-steps:
  stage: final
  allow_failure: true
  script:
  - kubectl delete namespace testing
