stages:
  - preparation
  - build
  - test
  - final
  
Pre:
  stage: preparation
  script:
  - apt-get update
  - apt-get install -y apt-transport-https
  - apt-get install -y curl
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - touch /etc/apt/sources.list.d/kubernetes.list 
  - echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubectl

Job1:
  stage: build
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - echo "HARAMBE VS BOKITO DEATHMATCH"
  
Job2:
  stage: build
  script:
  - echo "FLOQUET DE NEU JUMPS INTO THE RING"
  
Job3:
  stage: test
  script:
  - echo "WOOOOOOOAARGGGGGGG"
  - date
  - sleep 5
  - date
 
Final:
  stage: final
  script:
  - kubectl get namespaces
  
