stages:
  - preparation
  - build
  - test
  - final
  
Pre:
  stage: preparation
  script:
  - kubectl proxy --port=8080 &
  - curl http://localhost:8080/api/

Job1:
  stage: build
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - echo "HARAMBE VS BOKITO DEATHMATCH"
  
Job2:
  stage: build
  script:
  - echo "FLOQUET DE NEU JUMPS INTO THE RING"
  
Job3:
  stage: test
  script:
  - echo "WOOOOOOOAARGGGGGGG"
  - date
  - sleep 5
  - date
 
Final:
  stage: final
  script:
  - kubectl get namespaces
  
