---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubekat-pvc-checker
  labels:
    app: kubekat-pvc-checker
    sla: low
    maintainer: "xtorrent"
    team: SRE
spec:
  selector:
    matchLabels:
      app: kubekat-pvc-checker
  replicas: 1
  template:
    metadata:
      labels:
        app: kubekat-pvc-checker
    spec:
      serviceAccountName: kubekat-pvc-checker
      containers:
      - name: kubekat-pvc-checker
        image: sendotux/kubekat-pvc-checker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: kubekat-pvc-checker-configmap
