---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubekat-pvc-checker
  name: kubekat-pvc-checker
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kubekat-pvc-checker
