---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-label-checker
  labels:
    app: kubernetes-label-checker
    sla: "critical"
    maintainer: "Sjaak_S_PhD"
    team: "Katten"
spec:
  selector:
    matchLabels:
      app: kubernetes-label-checker
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-label-checker
    spec:
      containers:
      - name: kubernetes-label-checker
        image: sendotux/kubernetes-label-checker:latest
        ports:
        - containerPort: 5000
