---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubekat
  name: kubekat
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kubekat

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubekat
spec:
  rules:
  - host: label-checker.home.sendotux.net
    http:
      paths:
      - backend:
          serviceName: kubekat
          servicePort: 80
        path: /
  tls:
  - hosts:
    - label-checker.home.sendotux.net
    secretName: wildcard.home.sendotux.net
