---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubekat


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubekat
subjects:
- kind: ServiceAccount
  name: kubekat
  namespace: kubekat
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: "rbac.authorization.k8s.io"
